### ISSUE TITLE
Upgrade to JaCoCo 0.8.0

### ISSUE THREAD

**Issue by rmcloughlin** [sbt/sbt-jacoco#106]
JaCoCo 0.8.0 is out now:  https://github.com/jacoco/jacoco/releases

sbt-jacoco currently depends on version 0.7.9

**Comment by stijndehaes** [comment]
I quickly tried the upgrade and got two compile errors one was easily fixed. By using 
`CRC64.classId(..)` instead of `CRC64.checksum(..)`.

The other compile error is also in the class FilteringClassAnalyzer on line 67 a new MethodAnalyzer is returned except in jacoco 0.8.0 the constructor for this method is not publicly accessible anymore. And I don't know what to change this to without spending more effort. Anybody else has a some more info?

**Comment by dbhatte** [comment]
I also tried the same. But, it cannot be done as we are relying on the internal implementation.
See the bug report that I raised on jacoco
https://github.com/jacoco/jacoco/issues/698#issuecomment-398157412

We will need to refactor the sbt-jacoco codebase. Anybody wants to take this up?

**Comment by marchof** [comment]
I'm a developer from the JaCoCo project. I see sbt depends on internals because it implements its own filters for Scala artifacts.

At JaCoCo we now have many filters in place, e.g. for Kotlin, Lombok etc. What about contributing Scala filters to the JaCoCo project?

**Comment by stringbean** [comment]
Thanks for the input @marchof.

When I took over the project the filters were still in the early stages of development. Now that they've shipped I'll take a look and see what we can do!

**Comment by dbhatte** [comment]
You solve this problem by overriding the Jacoco version in the plugins.sbt
e.g. 
`dependencyOverrides  ++= Seq(
  "org.jacoco"                  %  "org.jacoco.core"      % "0.8.2",
  "org.jacoco"                  %  "org.jacoco.report"    % "0.8.2",
)`

This also solves the problem of making Jacoco work with Java 10

**Comment by raboof** [comment]
It looks like this was achieved by #119 ?

**Comment by dbhatte** [comment]
Yes, I think so

**Comment by SahilAggarwalG** [comment]
when new version of sbt-jacoco will release with jacoco 0.8.2

**Comment by SahilAggarwalG** [comment]
> You solve this problem by overriding the Jacoco version in the plugins.sbt
> e.g.
> `dependencyOverrides ++= Seq( "org.jacoco" % "org.jacoco.core" % "0.8.2", "org.jacoco" % "org.jacoco.report" % "0.8.2", )`
> 
> This also solves the problem of making Jacoco work with Java 10

when i did this i got the following error : 
java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_28bab1d/Offline,

**Comment by demjened** [comment]
@SahilAggarwalG I managed to get JaCoCo working with Java 11 / Scala 2.12.8 / SBT 1.2.8 by making the following changes:
```
// plugins.sbt
val jacocoVersion = "0.8.2"

dependencyOverrides ++= Seq(
  "org.jacoco" % "org.jacoco.core" % jacocoVersion,
  "org.jacoco" % "org.jacoco.report" % jacocoVersion,
  "org.jacoco" % "org.jacoco.agent" % jacocoVersion)

// build.sbt
val jacocoVersion = "0.8.2"

dependencyOverrides ++= Seq(
  "org.jacoco" % "org.jacoco.core" % jacocoVersion % Test,
  "org.jacoco" % "org.jacoco.report" % jacocoVersion % Test,
  "org.jacoco" % "org.jacoco.agent" % jacocoVersion % Test)
```
(Maybe some of these can be left out, I haven't tried.)

That said, getting `sbt-jacoco` work on Java 11 without this hack would be really great, so I'm looking forward to the 4.0 release. This is the best plugin for SBT/JaCoCo and I haven't found any alternatives that currently support Java 11. cc @stringbean

**Comment by eed3si9n** [comment]
Closing this as fixed in https://github.com/sbt/sbt-jacoco/pull/119
